spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop # 시작 시 @Table 클래스대로 DB에 만들어버림. none으로 하면 안 만듬
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

index:
  page: "/api/swagger-ui.html"

swagger:
  base-path: "/"